# Lab-5

### extracting tables from HTML pages

In [114]:
import pandas as pd
s=pd.read_html('https://en.wikipedia.org/wiki/List_of_weather_records')
len(s)

19

In [115]:
s[0]

Country/Region         Temperature  \
0                                             Algeria  51.3 °C (124.3 °F)   
1                                            Botswana  44.0 °C (111.2 °F)   
2                                        Burkina Faso  47.2 °C (117.0 °F)   
3                                                Chad  47.6 °C (117.7 °F)   
4                                             Comoros   36.0 °C (96.8 °F)   
5                                Eswatini (Swaziland)  47.4 °C (117.3 °F)   
6                                              Gambia  49.0 °C (120.2 °F)   
7                                               Ghana  43.8 °C (110.8 °F)   
8                                              Guinea  45.0 °C (113.0 °F)   
9                                          Madagascar  43.6 °C (110.5 °F)   
10  Morocco (then the French protectorate in Morocco)  51.7 °C (125.1 °F)   
11                                              Niger  49.5 °C (121.1 °F)   
12                                            Nigeria  46.4 °C (115.5 °F)   
13                                            Réunion   36.9 °C (98.4 °F)   
14      South Africa (then the Union of South Africa)  50.0 °C (122.0 °F)   
15                                              Sudan  49.7 °C (121.5 °F)   
16  Tunisia (then the French protectorate of Tunisia)      55 °C (131 °F)   
17           Western Sahara (then the Spanish Sahara)  50.7 °C (123.3 °F)   
18                                             Zambia  42.4 °C (108.3 °F)   

                                        Town/Location  \
0   El Bayadh, El Bayadh ProvinceOuargla, Ouargla ...   
1                                                Maun   
2                                                Dori   
3                                        Faya-Largeau   
4                        Hahaya International Airport   
5                                            Lavumisa   
6                                               Jenoi   
7                                            Navrongo   
8                               Koundara, Boké Region   
9                             Ejeda, Atsimo-Andrefana   
10                                           Inezgane   
11                                              Diffa   
12                                               Yola   
13                                            Le Port   
14                             Dunbrody, Eastern Cape   
15                                            Dongola   
16                                             Kebili   
17                                             Semara   
18                            Mfuwe, Eastern Province   

                                   Date  
0   2 September 1979[18]5 July 2018[19]  
1                7 January 2016[20][21]  
2                              1984[22]  
3                      22 June 2010[23]  
4                  15 November 2017[24]  
5                                 ?[25]  
6                              2001[26]  
7                     26 March 2017[24]  
8                     29 March 2017[24]  
9                                 ?[27]  
10                   19 August 1940[28]  
11                 7 September 1978[29]  
12        3 April 2010[citation needed]  
13                     6 March 2004[30]  
14          3 November 1918[31][note 1]  
15                     25 June 2010[23]  
16              7 July 1931[33][note 2]  
17                     13 July 1961[34]  
18                  13 October 2010[23]

In [116]:
import numpy as np
a = np.array([1,2,3])
print(a)
a = np.array([[1,2],[3,4]])
print(a)
a = np.array([1,2,3,4,5], ndmin = 2)
print(a)
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


In [117]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [118]:
a.ndim #shows no. of dimensions

2

In [119]:
a.shape=(3,2) #fits the array to a particular shape 
a 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
b=a.reshape(2,3) #reshaping the array to fit it into a particular shape
b

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
a=np.arange(24) #arranges the array upto the given no.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [122]:
x=np.arange(10,20,2) # arranges from the lower limit to the upper limit with a gap given
x

array([10, 12, 14, 16, 18])

In [123]:
b=a.reshape(2,4,3) #it makes an Array of 2 X 4 X 3
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [124]:
x=np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [125]:
x=np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [126]:
x=np.empty([3,2], dtype=int)
print(x)
# x = np.zeros(5)
# print(x)
# x = np.zeros((5,), dtype=int)
# print(x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [127]:
x=np.ones([2,2], dtype=int)
x

array([[1, 1],
       [1, 1]])

In [128]:
x=[1,2,3]
a=np.asarray(x)
a

array([1, 2, 3])

In [129]:
list=range(5)
it=iter(list)
x=np.fromiter(it, dtype=float)
x

array([0., 1., 2., 3., 4.])

In [130]:
for x in np.nditer(a):
    print(x)
a=np.arange(10)
s=slice(2,7,2) # slice (start ,stop , step)
print(a[s])
b=a[2:7:2]
print(b)

1
2
3
[2 4 6]
[2 4 6]


In [131]:
print(a)
print('The items in the second column are:')
print(a[...,1])
print('The items in the second row are:')
print(a[1,...])
# Now we will slice all items from column 1 onwards
print('The items column 1 onwards are:')
print(a[...,1:])

[0 1 2 3 4 5 6 7 8 9]
The items in the second column are:
1
The items in the second row are:
1
The items column 1 onwards are:
[1 2 3 4 5 6 7 8 9]


In [132]:
print('Array containing sine values:')
sin=np.sin(a*np.pi/180)
print(sin)
print('Compute sine inverse of angles. Returned values are in radians.')
inv=np.arcsin(sin)
print(inv)

Array containing sine values:
[0.         0.01745241 0.0348995  0.05233596 0.06975647 0.08715574
 0.10452846 0.12186934 0.1391731  0.15643447]
Compute sine inverse of angles. Returned values are in radians.
[0.         0.01745329 0.03490659 0.05235988 0.06981317 0.08726646
 0.10471976 0.12217305 0.13962634 0.15707963]


In [133]:
x=np.array([1,2,3,4,1,2,5])
print(np.bincount(x))

[0 2 2 1 1 1]


In [134]:
print('Check result by converting to degrees:')
print(np.degrees(inv))
print('arccos and arctan functions behave similarly:')
cos=np.cos(a*np.pi/180)
print(cos)
print('Inverse of cos:')
inv=np.arccos(cos)
print(inv)

Check result by converting to degrees:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
arccos and arctan functions behave similarly:
[1.         0.9998477  0.99939083 0.99862953 0.99756405 0.9961947
 0.9945219  0.99254615 0.99026807 0.98768834]
Inverse of cos:
[0.         0.01745329 0.03490659 0.05235988 0.06981317 0.08726646
 0.10471976 0.12217305 0.13962634 0.15707963]


In [135]:
x=np.array([[1,2],[3,4]])
print(x.flatten())

[1 2 3 4]


In [136]:
x=np.array([[1,2],[3,4]])
print(x.ravel())

[1 2 3 4]


In [137]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [138]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np

img=cv.imread('image.jpeg', 1) # 1->colored, 0->grayscale, -1->unchanged
print(type(img))
print(img.shape)
px=img[100,100] # pixel values of three channels
print(px)

cv.imshow('Image', img)
cv.waitKey()
cv.destroyAllWindows()

<class 'numpy.ndarray'>
(853, 1280, 3)
[ 11 147 243]


In [139]:
# displays the grayscale image
b,g,r=cv.split(img)
b=img[:,:,0]
g=img[:,:,1]
r=img[:,:,2]
cv.imshow('Image',r)
cv.waitKey()
cv.destroyAllWindows()

In [140]:
# displays the negative grayscale image
# a,b,c=img.shape
# print(a,b,c)
# for i in (0,a-1):
#     for j in (0,b-1):
#         for k in (0,c-1):
#             img2[i,j,k]=255-img[i,j,k]
b1=255-b
g1=255-g
r1=255-r
img2=cv.merge((b1,g1,r1))
cv.imshow('Image',img2)
cv.waitKey()
cv.destroyAllWindows()

In [141]:
b[[100:200],[100:200]]=0
g[[100:200],[100:200]]=0
r[[100:200],[100:200]]=0
img2=cv.merge((b,g,r))
cv.imshow('Image',img2)
cv.waitKey()
cv.destroyAllWindows()

SyntaxError: invalid syntax (3480252620.py, line 1)